#!/bin/sh

### BEGIN INIT INFO
# Provides:          sniffer-app-ctl
# Required-Start:    #adjust
# Required-Stop:     #adjust
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
 
DESC="Sniffer Startup Script Deamon"
NAME="sniff"

case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	sniff -dl6
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME"
	killall -9 sniff
	echo "."
	;;
  restart)
	echo -n "Restarting $DESC: $NAME"
	killall -9 sniff
	sleep 1
	sniff -dl6
	echo "."
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0

